using OWOGame;
/*
    /!\ DO NOT MODIFY THIS FILE DIRECTLY /!\

    This file is auto-generated by OWOVRC.MuscleGenerator.
    To update the muscle list, update the OWO dependency for ALL PROJECTS and run OWOVRC.MuscleGenerator.
*/
namespace OWOVRC.Classes.OWOSuit
{
    public static partial class OWOMuscles
    {
        //NOTE: Auto-Generated muscle list
        public static Muscle? GetMuscle(string name)
        {
            return name.ToLower() switch
            {
                "owo_suit_pectoral_r" => Muscle.Pectoral_R,
                "pectoral_r" => Muscle.Pectoral_R,
                "owo_suit_pectoral_l" => Muscle.Pectoral_L,
                "pectoral_l" => Muscle.Pectoral_L,
                "owo_suit_abdominal_r" => Muscle.Abdominal_R,
                "abdominal_r" => Muscle.Abdominal_R,
                "owo_suit_abdominal_l" => Muscle.Abdominal_L,
                "abdominal_l" => Muscle.Abdominal_L,
                "owo_suit_arm_r" => Muscle.Arm_R,
                "arm_r" => Muscle.Arm_R,
                "owo_suit_arm_l" => Muscle.Arm_L,
                "arm_l" => Muscle.Arm_L,
                "owo_suit_dorsal_r" => Muscle.Dorsal_R,
                "dorsal_r" => Muscle.Dorsal_R,
                "owo_suit_dorsal_l" => Muscle.Dorsal_L,
                "dorsal_l" => Muscle.Dorsal_L,
                "owo_suit_lumbar_r" => Muscle.Lumbar_R,
                "lumbar_r" => Muscle.Lumbar_R,
                "owo_suit_lumbar_l" => Muscle.Lumbar_L,
                "lumbar_l" => Muscle.Lumbar_L,

                _ => null,
            };
        }
    }
}