namespace OWOVRC.MuscleGenerator.Classes
{
    internal static class ClassTemplate
    {
        public const string ClassText = @"using OWOGame;
/*
    /!\ DO NOT MODIFY THIS FILE DIRECTLY /!\

    This file is auto-generated by OWOVRC.MuscleGenerator.
    To update the muscle list, update the OWO dependency for ALL PROJECTS and run OWOVRC.MuscleGenerator.
*/
namespace OWOVRC.Classes.OWOSuit
{
    public static partial class OWOMuscles
    {
        //NOTE: Auto-Generated muscle list
        public static Muscle? GetMuscle(string name)
        {
            return name.ToLower() switch
            {
//<AUTOGEN: MuscleFunction>
                _ => null,
            };
        }
    }
}";
    }
}