name: .NET Core Desktop

on:
  push:
    branches: [ "master", "AdvancedSensationBuilder" ]
  pull_request:
    branches: [ "master", "AdvancedSensationBuilder" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: OWOVRC.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test

    # Build the app
    - name: Publish OWOVRC.UI
      run: dotnet publish "OWOVRC.UI/OWOVRC.UI.csproj" -r win-x64 -o "OWOVRC/bin/publish/win-x64/" -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=false --self-contained false
    - name: Publish OWOVRC.CLI
      run: dotnet publish "OWOVRC.CLI/OWOVRC.CLI.csproj" -r win-x64 -o "OWOVRC/bin/publish/win-x64/" -p:PublishReadyToRun=true -p:PublishTrimmed=true -p:PublishAOT=true --self-contained false

    # Upload the EXE https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OWOVRC
        path: "OWOVRC/bin/publish/win-x64/"
